name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discover-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: list
        run: |
          files=$(find .github/docker -type f -name 'Dockerfile*' | jq -R . | jq -s .)
          echo "files=$files" >> $GITHUB_ENV
          echo "files=$files" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: discover-dockerfiles
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Dockerfiles
        id: load-dockerfiles
        run: echo "FILES=${{ needs.discover-dockerfiles.outputs.files }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ fromJson(needs.discover-dockerfiles.outputs.files) != '[]' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ matrix.os }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ matrix.os }}-${{ github.sha }}
